#Copyright (c) 2011-2015 Hiroshi Tsubokawa
#See LICENSE and README

RM = rm -f
pyc_files := fujiyama.pyc

.PHONY: all clean depend
all:
	@echo -n

clean:
	@echo '  clean $(pyc_files)'
	@$(RM) $(pyc_files)

